### ISSUE TITLE
'Redmine Backlogs' plugin breaks out of theme.

### ISSUE THREAD

**Issue by ksavoie** [pixel-cookers/redmine-theme#23]
LOVE this theme but latest 'Redmine Backlogs' plugin breaks out of theme.
![screen shot 2013-08-21 at 11 56 33 am](https://f.cloud.github.com/assets/1609614/1002840/53d7c754-0a83-11e3-91e8-5c6972346da9.png)

**Comment by p-schneider** [comment]
Sorry for the late reply - just in case you did not already find a workaround or someone else like me had the same problem and used google to find this ticket. (I just installed redmine backlogs today, ran into this problem and used google to get to this ticket.)

open ~~public/plugin_assets/redmine_backlogs/stylesheets/global.css~~ `plugins/redmine_backlogs/assets/stylesheets/global.css` and find

``` css
/* MAIN */
#main{
  display:block;
  height:100%;
  width:100%;
  margin: 0; /*yes, we do!*/
}
```

uncomment the block e.g.

``` css
/* MAIN */
#main{
  /*display:block;
  height:100%;
  width:100%;
  margin: 0; /*yes, we do!*/
}
```

edit: you might also want to edit the file in `public/plugin_assets/...` if it does not update automatically, but you should definitely edit the file in `plugins/redmine_backlogs/...`
