### ISSUE TITLE
Bad positioning of the toc in Wiki pages

### ISSUE THREAD

**Issue by hriekehof** [pixel-cookers/redmine-theme#35]
If i include a {{<toc}} on a wiki page it has a strange positioning inside the wiki page. You can improve it by putting it under an .h1 but it still is not so nice placed.

Would be great if the positioning could be improved :)

**Comment by nick7ikin** [comment]
+1

**Comment by u1735067** [comment]
Same with right positionned toc {{>toc}} sadly :(
If anyone has a working CSS workaound to fix this I'll gladly take it too.

**Comment by u1735067** [comment]
Best hack I could find (I don't like CSS) : 

``` css
/* Ugly hack par Alex` */
.contextual {
  position:  absolute !important;
  right: 20%;
  top: 86px;
}
.toc.right {
  margin-top: 55px;
}
```
